# Generated by Django 4.0.7 on 2022-09-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название курса')),
                ('descriptions', models.TextField(verbose_name='Описание курса')),
                ('create_id', models.DateTimeField(verbose_name='Дата начало курсов')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('mail', models.CharField(max_length=100, verbose_name='Эл. почта')),
                ('create_id', models.DateTimeField(verbose_name='Дата вступления')),
                ('description', models.TextField(verbose_name='Опыт/стэк технологий')),
                ('position', models.CharField(choices=[('P', 'Копирайтер/наполнение контента/SMM специалист'), ('S', 'Отдел продаж'), ('A', 'Системный администратор'), ('P', 'PM Менеджер'), ('FRONT', 'Frontend'), ('BACK', 'Backend'), ('FULL', 'Fullstack'), ('TEST', 'Тестировщик'), ('LAYOUT', 'Верстальщик'), ('W', 'Web дизайнер')], default='P', max_length=10, verbose_name='Должность')),
                ('rate', models.IntegerField(verbose_name='Ставка в час')),
                ('knowledgeLevel', models.CharField(choices=[('J', 'JUNIOR'), ('M', 'MIDDLE'), ('S', 'SENIOR')], default='J', max_length=5, verbose_name='Уровень знаний')),
                ('link', models.TextField(verbose_name='Ссылка на соц сети')),
                ('visit', models.TextField(verbose_name='Посещения')),
                ('courses', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='Projects.courses', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название проекта')),
                ('create_id', models.DateTimeField(verbose_name='Дата создания')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('stage', models.CharField(choices=[('0', 'Ведутся переговоры'), ('1', 'Подписание договора'), ('2', 'В разработке'), ('4', 'Сдача проекта'), ('6', 'Отказ'), ('7', 'В заморозке')], default='0', max_length=1, verbose_name='Стадия')),
                ('notes', models.TextField(verbose_name='Заметки')),
                ('persons', models.ManyToManyField(to='Projects.person', verbose_name='Состав сотрудников')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='TasksProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('create_id', models.DateTimeField(verbose_name='Дата начала задачи')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.person', verbose_name='Сотрудник')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'TasksProjects',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ManyToManyField(blank=True, to='Projects.projects', verbose_name='Проекты'),
        ),
    ]
