# Generated by Django 4.0.7 on 2022-09-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.TextField(verbose_name='Название проекта'),
        ),
    ]
