# Generated by Django 4.0.7 on 2022-09-12 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_projects_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.IntegerField(blank=True, verbose_name='Копирайтер/наполнение контента/SMM специалист')),
                ('sale', models.IntegerField(blank=True, verbose_name='Отдел продаж')),
                ('admin', models.IntegerField(blank=True, verbose_name='Системный администратор')),
                ('project_manage', models.IntegerField(blank=True, verbose_name='PM Менеджер')),
                ('backend', models.IntegerField(blank=True, verbose_name='Backend')),
                ('frontend', models.IntegerField(blank=True, verbose_name='Frontend')),
                ('fullstack', models.IntegerField(blank=True, verbose_name='Fullstack')),
                ('test', models.IntegerField(blank=True, verbose_name='Тестировщик')),
                ('layout', models.IntegerField(blank=True, verbose_name='Верстальщик')),
                ('web_designer', models.IntegerField(blank=True, verbose_name='Web дизайнер')),
                ('manager_1', models.IntegerField(blank=True, verbose_name='Управленец 1(Максим)')),
                ('manager_2', models.IntegerField(blank=True, verbose_name='Упраленец 2(Дмитрий)')),
                ('manager_3', models.IntegerField(blank=True, verbose_name='Управленец 3(Валерий)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Projects.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Смет',
                'db_table': 'Estimate',
            },
        ),
    ]
