# Generated by Django 4.0.7 on 2022-09-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_estimate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'verbose_name': 'Смета', 'verbose_name_plural': 'Сметы'},
        ),
        migrations.AlterField(
            model_name='estimate',
            name='admin',
            field=models.IntegerField(default=0, verbose_name='Системный администратор'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='backend',
            field=models.IntegerField(default=0, verbose_name='Backend'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='frontend',
            field=models.IntegerField(default=0, verbose_name='Frontend'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='fullstack',
            field=models.IntegerField(default=0, verbose_name='Fullstack'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='layout',
            field=models.IntegerField(default=0, verbose_name='Верстальщик'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='manager_1',
            field=models.IntegerField(default=0, verbose_name='Управленец 1(Максим)'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='manager_2',
            field=models.IntegerField(default=0, verbose_name='Упраленец 2(Дмитрий)'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='manager_3',
            field=models.IntegerField(default=0, verbose_name='Управленец 3(Валерий)'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='project_manage',
            field=models.IntegerField(default=0, verbose_name='PM Менеджер'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='promotion',
            field=models.IntegerField(default=0, verbose_name='Копирайтер/наполнение контента/SMM специалист'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='Отдел продаж'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='test',
            field=models.IntegerField(default=0, verbose_name='Тестировщик'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='web_designer',
            field=models.IntegerField(default=0, verbose_name='Web дизайнер'),
        ),
    ]
